# Generated by Django 4.2.8 on 2024-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
