# Generated by Django 4.2.8 on 2023-12-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('is_listed', models.BooleanField(default=True)),
                ('product_offer', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category_offer', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_products.products')),
            ],
        ),
    ]
