# Generated by Django 4.2.8 on 2023-12-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0002_colorvarient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colour',
        ),
    ]
