# Generated by Django 4.2.8 on 2023-12-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0003_remove_products_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product_id',
        ),
        migrations.AddField(
            model_name='image',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_products.colorvarient'),
        ),
    ]
