# Generated by Django 4.2.8 on 2023-12-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0004_remove_image_product_id_image_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
