# Generated by Django 4.2.8 on 2023-12-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0005_remove_products_price_remove_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='varient',
        ),
        migrations.AddField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_products.colorvarient'),
        ),
    ]
