# Generated by Django 4.2.8 on 2023-12-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0007_alter_colorvarient_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvarient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorvarient_set', to='user_products.products'),
        ),
    ]
