# Generated by Django 4.2.8 on 2024-01-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0008_alter_colorvarient_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvarient',
            name='category_offer',
        ),
    ]
