# Generated by Django 4.2.8 on 2024-01-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_products', '0008_alter_colorvarient_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='banner')),
                ('is_listed', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_products.colorvarient')),
            ],
        ),
    ]
