# Generated by Django 4.2.8 on 2024-01-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0008_alter_colorvarient_product'),
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baners',
            new_name='Banner',
        ),
    ]
