from django.urls import path
from . import views


urlpatterns = [
    path('admin_login/',views.admin_loginn,name='admin_login'),
    path('admin_logout',views.admin_logoutt,name='admin_logout'),
    path('dashboard/',views.dashboardd,name='dashboard'),
    path('users/',views.userss,name='users'),
    path('products',views.productss,name='products'),
    path('add_product',views.add_productss,name='add_product'),
    path('category',views.categoriess,name='category'),
    path('brands',views.brandss,name='brands'),
    path('add_brands',views.add_brandss,name='add_brands'),
    path('add_category',views.add_categoryy,name='add_category'),
    path('add_variants/<str:id>/',views.add_variantss,name='add_variants'),
    path('variants/<str:id>/', views.variantss, name='variants'),
    path('edit_variants/<str:id>/',views.edit_variantss,name='edit_variants'),
    path('edit_product/<str:id>',views.edit_productss,name='edit_product'),
    path('edit_brands/<str:id>',views.edit_brandss,name='edit_brands'),
    path('edit_category/<str:id>',views.edit_categoryy,name='edit_category'),
    path('user_status/<str:id>',views.user_statuss,name='user_status'),
    path('category_status/<str:id>',views.category_statuss,name='category_status'),
    path('brand_status/<str:id>',views.brand_statuss,name='brand_status'),
    path('product_status/<str:id>',views.product_statuss,name='product_status'),
    path('variant_status/<str:id>',views.variant_statuss,name='variant_status'),
    path('admin_order/',views.admin_orderr,name='admin_order'),
    path('order_view/<str:order_id>/<str:id>/',views.order_vieww,name='order_view'),
    path('sales_report/', views.sales_report, name='sales_report'),
    path('download_exel',views.excel_report,name="download_exel"),
    path('pdf_download',views.DownloadPDF.as_view(),name='pdf_download'),
    path('banner',views.banner,name='banner'),
    path('add_banner',views.add_banner,name='add_banner'), 
    path('edit_banner/<str:id>/',views.edit_banner,name='edit_banner'), 
    path('banner_status/<str:id>/',views.banner_status,name='banner_status'),
    path('coupon',views.coupon,name='coupon'),
    path('add_coupon',views.add_coupon,name='add_coupon'), 
    path('edit_coupon/<str:id>/',views.edit_coupon,name='edit_coupon'), 
    path('coupon_status/<str:id>/',views.coupon_status,name='coupon_status'),
    path('offers/',views.offers,name='offers'),
    path('add_offer/',views.add_offer,name='add_offer'),
    path('edit_offer/<str:id>/',views.edit_offer,name='edit_offer'),
    path('offer_delete/<str:id>/',views.offer_delete,name='offer_delete'),
    path('category_offer',views.category_offer,name='category_offer'),
    path('add_category_offer',views.add_category_offer,name='add_category_offer'),
    path('cancel_category_offer/<str:id>/',views.cancel_category_offer,name='cancel_category_offer'),

]