# Generated by Django 4.2.8 on 2023-12-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
