# Generated by Django 4.2.8 on 2024-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='Pending', max_length=150),
        ),
    ]
