# Generated by Django 4.2.8 on 2024-01-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_products', '0009_remove_colorvarient_category_offer'),
        ('user_coupon', '0001_initial'),
        ('user_order', '0003_order_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_coupon.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_products.colorvarient'),
        ),
    ]
